sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5

# S1989: Handle exceptions in servlets. Tomcat handles unchecked exceptions naturally via 500 error page.
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1989
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java

# S2143: Use java.time. The project uses JDBC java.sql.Date/Time which natively binds to DB without converters.
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S2143
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java

# S8688: Explicitly specify time zone for .now(). System default is expected here.
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S8688
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.java

# S4507: e.printStackTrace() is a debug feature. Ignoring since we don't have a configured logger framework.
sonar.issue.ignore.multicriteria.e4.ruleKey=java:S4507
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.java

# S6840: street-address is a valid HTML autocomplete value per the HTML spec.
sonar.issue.ignore.multicriteria.e5.ruleKey=Web:S6840
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.jsp
